spring:
  profile.active: dev
  datasource:
    url: jdbc:mysql://localhost/foroalura1
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}
